---
title: "My Garlic Garden"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```
## A gift poorly spent
In 2022, my co-worker gave me a few bulbs of his famously delicious, hard-neck variety of garlic. The cloves were HUGE! And they lived up to their reputation for flavor! I used every last one, which was a big mistake. 

## A second chance 
When he gave me a sample from his 2023 harvest, I made sure to save a few for planting (with his permission). Now, in 2024, I'm planting my second year of this delicious, large-clove variety of garlic. 

## Cultivating Data
I'm also a scientist looking for better ways to communicate data. So, I'm turning my little garlic garden into an experiment. I've heard that planting larger cloves leads to larger bulbs at harvest. In the 2024-2025 year, I'm tracking the size and position of the garlic to see how it affects growth. I may take inspiration from the common "iris" dataset and take measurements of the plants as well as the cloves at harvest.

## Reports
Here are some links to a couple reports I made. These are for me to practice and they can serve as a source for people learning R.

- [Colossal Cloves](./Colossal-Cloves.html)
- [Reap What You Sow](./Reap-what-you-Sow.html)


